version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          command: |
            aws cloudformation deploy  --stack-name DeployTest-6b012 --region us-east-1 --template-file aws_cd_infra_test/CD_AWS_Test.yml --parameter-overrides file://aws_cd_infra_test/CD_AWS_Test.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

  Config_Machine:
    docker: 
      #- image: ansible/ansible
      - image: python:3.7-alpine3.11
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["91:64:2e:b9:ff:6b:f4:88:14:4e:02:f7:77:8b:09:93:7e:1f:f3:f2"] 
      - run: 
          command: |
            apk add --update ansible
      - run: 
          command: |
            ansible-playbook -i ansible_playbooks/inventory/hosts ansible_playbooks/Main.yml
            

workflows:
  aws_test:
    jobs:
      - create_infrastructure
      - Config_Machine:
          requires:
            - create_infrastructure
