version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_DEFAULT_REGION
      - run: 
          command: |
            aws cloudformation deploy  --stack-name DeployTest-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1 --template-file aws_cd_infra_test/CD_AWS_Test.yml --parameter-overrides file://aws_cd_infra_test/CD_AWS_Test.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
            

workflows:
  aws_test:
    jobs:
      - create_infrastructure
      #- Test_Cash_restore:
       #   requires:
        #    - Test_Cash_create
