version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

commands:
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y

jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          command: |
            aws cloudformation deploy  --stack-name DeployTest-6b012 --region us-east-1 --template-file aws_cd_infra_test/CD_AWS_Test.yml --parameter-overrides file://aws_cd_infra_test/CD_AWS_Test.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

  Config_Machine:
    docker: 
      - image: cimg/base:stable
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["00:35:2d:41:87:37:9c:6e:25:9a:48:2d:9e:db:04:5f"] 
      - install_ansible
      - run: 
          command: |
            ansible-playbook -i ansible_playbooks/inventory/hosts.txt ansible_playbooks/Main.yml

workflows:
  aws_test:
    jobs:
      #- create_infrastructure
      - Config_Machine
          #requires:
           # - create_infrastructure