version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          command: |
            aws cloudformation deploy  --stack-name DeployTest-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1 --template-body file://aws_cd_infra_test/CD_AWS_Test.yml --parameters file://aws_cd_infra_test/CD_AWS_Test.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
            

workflows:
  aws_test:
    jobs:
      - create_infrastructure
      #- Test_Cash_restore:
       #   requires:
        #    - Test_Cash_create
