version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  create_infrastructure:
    docker: 
      - image: amazon/aws-cli
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run: 
          command: |
            aws cloudformation deploy  --stack-name DeployTest-6b012 --region us-east-1 --template-file aws_cd_infra_test/CD_AWS_Test.yml --parameter-overrides file://aws_cd_infra_test/CD_AWS_Test.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

  Config_Machine:
    docker: 
      #- image: ansible/ansible
      - image: python:3.7-alpine3.11
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["00:35:2d:41:87:37:9c:6e:25:9a:48:2d:9e:db:04:5f"] 
      - run: 
          command: |
            apk add --update ansible
      - run: 
          command: |
            apk add tree
            tree -a /root
      - run: 
          command: |
            chmode 660 connect.pem
            ansible-playbook -vvv -i /root/project/ansible_playbooks/inventory/hosts.txt ansible_playbooks/Main.yml

  ssh_Machine:
      docker: 
        - image: alpine
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["00:35:2d:41:87:37:9c:6e:25:9a:48:2d:9e:db:04:5f"] 
        - run: 
            command: |
              hostname
              whoami
              ssh ubuntu@34.224.71.233
            

workflows:
  aws_test:
    jobs:
    #  - create_infrastructure
    #  - Config_Machine
    #      requires:
    #        - create_infrastructure
      - ssh_Machine
