---
  - name: install and configure apache2
    become: true
    apt:
      name: apache2 
      state: latest
  
  - name: Copy index.js
    become: true
    copy:
      backup: yes
      dest: /var/www/html/index.html
      src: index.html
  
  - name: Start & Enable service
    become: true
    systemd:
      name: apache2
      state: started
      enabled: yes
